name: Update docker image and helm chart

on:
    pull_request:
        branches:
            - develop
            - main
        types: [closed]


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        
        - name: Login to Docker
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_SECRET }}

        - name: Build Docker image
          run: docker build -t geonhyukseo/goormnes:${{ github.sha }} .

        - name: Push Docker image
          run: docker push geonhyukseo/goormnes:${{ github.sha }}

            